"""A-08: the two-pane web page. FastAPI serves a scan that already happened.

RULE, and it is the whole shape of this module: **the page reads, it does not decide.**
Nothing here judges anything. `GET /api/report` serves `reports/latest.json` verbatim;
`POST /api/lint` runs A-03's extractor and A-04's judge and hands back what they produced.
Every row that reaches the browser still carries the `rule_fired` that `judge.py` stamped on it.

Three things this module deliberately does NOT do:

1. **It does not scan on load.** `reports/latest.json` is a build artifact (gitignored,
   regenerated by `almanac scan`). A scan is ~30s of live model calls; a page that scanned on
   page-view would bill every visitor to Zaeem's API key. `/api/report` reads the file or says
   plainly that it is missing.
2. **It does not re-implement the pipeline.** `/api/lint` goes through `extract.read_source` and
   `cli._judged`, so a verdict on the page is the same object `almanac lint` prints. A second
   implementation here would be a second thing to keep true.
3. **It does not write to YouTube, under any configuration.** See the write guard below.

## The write guard

The Project Rules allow `videos.update` only when ALMANAC_WRITE=true AND the channel is
ALMANAC_TEST_CHANNEL_ID AND the CLI was given `--apply`. **A web request has no `--apply`, and
there is no way for a visitor to supply one.** So `/api/apply` is dry-run *unconditionally*: it
does not read ALMANAC_WRITE, does not import `almanac.youtube`, and constructs no API client.
It composes the description a human would paste and returns the diff.

That is stronger than "off by default" — a flag flipped in the environment cannot turn it on,
which `tests/test_web.py` proves by running the endpoint with ALMANAC_WRITE=true and counting
`videos.update` calls at the `googleapiclient.discovery.build` chokepoint.

## What the page may claim

Bounded by `docs/decisions/ADR-002-eval-loop.md` (A-05). The measured figures live in
`MEASURED` below rather than in the HTML, so the page cannot drift from the eval table without
this constant changing. Nothing on the page may claim more than A-05 measured.
"""

from __future__ import annotations

import dataclasses
import difflib
import json
import tempfile
import time
from datetime import date, datetime
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse, JSONResponse
from pydantic import BaseModel, Field

REPO_ROOT = Path(__file__).resolve().parents[1]
STATIC_DIR = Path(__file__).resolve().parent / "static"
INDEX_HTML = STATIC_DIR / "index.html"
REPORT_PATH = REPO_ROOT / "reports" / "latest.json"
CORPUS_CHANNEL = REPO_ROOT / "corpus" / "channel"

# The issue's cap. Enforced on the decoded string, not on the request body, because a multi-byte
# character is one character to the person who pasted it.
MAX_LINT_CHARS = 8_000

# The pin every drafted note opens with. `notes.py` ASKS the model for it in the prompt and its
# fallback template hard-codes it, but `check_note()` does not enforce it — so this is the label
# the page uses for the note block, not an invariant anything may assert on a model-written note.
NOTE_MARKER = "📌"

# Every figure the page is allowed to quote, READ FROM THE EVAL RUN rather than transcribed here.
#
# The page's promise is "nothing on this page quotes a number that run did not produce". A hand-kept
# dict cannot keep that promise: this block previously carried Claude-era figures that stayed on the
# page after the engine moved to Gemini, and a sentence naming `temperature` as the cause of
# non-reproducibility that was false on both engines. Reading evals/results.json makes the promise
# structural — the page cannot quote a number no run produced, because it has no number of its own.
EVAL_RESULTS = Path(__file__).resolve().parents[1] / "evals" / "results.json"
REPRODUCIBILITY = Path(__file__).resolve().parents[1] / "evals" / "reproducibility.json"


def _pct(x: float) -> str:
    return f"{round(x * 100)}%"


def _over_extraction() -> dict:
    """Count repeats in the last scan, split by whether they are a defect or not.

    An earlier version of this counted every repeat of a value inside a source and called all of
    them over-reading. That was wrong by 13x: of the 26 it found, 24 were the same number claimed
    in DIFFERENT sentences -- "Raise it one point." and "One point a year is invisible" are two
    real claims, and collapsing them would destroy data. Only 2 were the actual defect, the same
    number pulled twice out of one sentence.

    `same_sentence` is now an invariant rather than a measurement: `_drop_same_sentence_repeats`
    enforces it at extraction. It is still counted here, because a guard nobody measures is a
    guard nobody notices failing.

    `reports/latest.json` is a gitignored build artifact and may be absent (fresh clone, or a
    deploy that has not scanned). MEASURED is built at import, so that must not stop the app.
    """
    blank = {"measured": False, "verdicts": 0, "same_sentence": 0, "across_sentences": 0,
             "surfaced_duplicates": 0}
    if not REPORT_PATH.is_file():
        return blank
    try:
        rep = json.loads(REPORT_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return blank

    from almanac.extract import discover_sources, sentence_index_of_quote

    sources = {}
    for video in rep.get("videos", []):
        sid = video.get("source_id", "")
        if sid and sid not in sources:
            root = Path(sid).parent.parent
            try:
                # Assigned key by key on purpose. tests/test_web.py bans the dotted mutate-call
                # spelling from this entire module -- comments included -- so that no YouTube write
                # call can hide anywhere in the web layer. The guard is crude and that is its
                # value; the merge below is written to keep the net whole rather than to poke a
                # hole in it for a dict.
                for found in discover_sources(str(root)):
                    sources[found.source_id] = found
            except (OSError, ValueError):
                return blank

    verdicts = same = across = surfaced_dupes = 0
    for video in rep.get("videos", []):
        source = sources.get(video.get("source_id", ""))
        seen: dict[tuple, list[int]] = {}
        surfaced: dict[tuple, int] = {}
        for v in video.get("verdicts", []):
            verdicts += 1
            if source is None:
                continue
            idx = sentence_index_of_quote(source, v.get("quote", ""))
            if idx is None:
                continue
            key = (v.get("claimed_value"), v.get("claim_type"))
            if key in seen:
                if idx in seen[key]:
                    same += 1
                else:
                    across += 1
            seen.setdefault(key, []).append(idx)
            if str(v.get("status", "")).startswith("stale_"):
                skey = (v.get("claimed_value"), v.get("entity_key"))
                surfaced[skey] = surfaced.get(skey, 0) + 1
        surfaced_dupes += sum(n - 1 for n in surfaced.values() if n > 1)

    return {"measured": True, "verdicts": verdicts, "same_sentence": same,
            "across_sentences": across, "surfaced_duplicates": surfaced_dupes}


def _load_measured() -> dict:
    """Derive the page's quotable figures from the committed eval run."""
    raw = json.loads(EVAL_RESULTS.read_text(encoding="utf-8"))
    rep = json.loads(REPRODUCIBILITY.read_text(encoding="utf-8"))
    over = _over_extraction()
    by_status = {row["status"]: row for row in raw["status_scores"]}
    run, hn = raw["run"], raw["hard_negatives"]
    stale = by_status["stale_material"]
    return {
        "source": (
            f"almanac eval, live run {raw['run_at'][:10]}, "
            f"{len(run['sources_read']) if isinstance(run.get('sources_read'), list) else run.get('sources_read', 7)} sources, "
            f"{run['labelled_rows']} human-labelled rows, gate "
            f"{'PASS' if raw['gate']['passed'] else 'FAIL'}"
        ),
        "extraction_recall": f"{_pct(raw['extraction_recall'])} ({run['matched']}/{run['labelled_rows']})",
        "claim_type_accuracy": _pct(raw["claim_type"]["accuracy"]),
        "stale_material_precision": f"{stale['precision']:.2f}",
        "stale_material_recall": f"{stale['recall']:.2f}",
        "hard_negative_false_positives": (
            f"{hn['false_positives']} of {hn['matched']} matched illustrative/historical rows"
        ),
        "skip_recall": f"{by_status['skip']['recall']:.2f}",
        "judge_status_disagreements": (
            f"{len(raw['misses'])} on {run['matched']} matched rows, across all five statuses"
        ),
        # Reproducibility is now MEASURED rather than assumed, so it is read from the sampling
        # artifact instead of asserted here. The old hard-coded `False` was written when extraction
        # ran on claude-opus-5 and genuinely did vary; on the current engine six consecutive live
        # runs produced byte-identical scored output. Neither the old claim nor the new one may be
        # a literal in this file — that is the drift this page exists to catch.
        # Deliberately NOT "identical across all N runs". The runs span two code states -- before
        # and after the D-2 same-sentence guard -- and they are byte-identical WITHIN each state,
        # not across them (115 verdicts became 111). Saying "all N" would be the same species of
        # overstatement as pooling two engines' runs into one sample.
        "reproducibility": (
            f"{rep['gate_passes']}/{rep['gate_runs']} gate PASS, and byte-identical scored output "
            f"within each measured state of the extractor ("
            + ", ".join(f"{b['gate_runs']} runs {b['label']}" for b in rep["blocks"])
            + ")"
        ),
        "extraction_repeats_identically": rep["identical_across_runs"],
        "reproducibility_scope": rep["scope_of_the_claim"],
        "extraction_variance": (
            f"{run['verdicts_produced']} verdicts this run; {run['unmatched_verdicts']} of them have "
            f"no labelled row, so the eval set covers part of what the pipeline emits"
        ),
        "known_defect": (
            (
                f"The extractor can pull the same number twice out of one sentence — "
                f"\u201cSay you go sixty forty, sixty percent stocks and forty percent bonds\u201d "
                f"once became four claims. The prompt already asked for one claim per number and "
                f"the model did not always comply, so it is enforced in code instead: repeats "
                f"inside a sentence are dropped, keeping the first. It is the second rule the code "
                f"enforces rather than requests — the coverage sweep re-reads any number-bearing "
                f"sentence the first pass returned nothing for, and this one stops that "
                f"thoroughness turning into double-counting. In the last scan that leaves "
                f"{over['same_sentence']} of {over['verdicts']} verdicts repeating a number within "
                f"a sentence. The {over['across_sentences']} repeats across different sentences "
                f"are left alone — those are second mentions, and they are real claims."
            )
            if over["measured"]
            else (
                "The extractor can pull the same number twice out of one sentence; repeats inside "
                "a sentence are dropped in code, keeping the first. No scan artifact is on disk in "
                "this deployment, so the page cannot show the current count."
            )
        ),
        "figures_predate_the_sweep": False,
        "sweep_measured_here": True,
        "unmeasured": (
            f"{len(raw['not_extracted'])} labelled rows produced no claim at all — every one of them "
            f"an illustrative or structural phrase the judge discards. The page shows what the run "
            f"found; it does not claim the run found everything."
        ),
    }


MEASURED = _load_measured()


app = FastAPI(title="Almanac", description="Checks the numbers in a back catalogue.")


# ------------------------------------------------------------------------------ request models


class LintRequest(BaseModel):
    text: str = Field(description="a script or caption block to check")


class ApplyRequest(BaseModel):
    source_id: str | None = Field(
        default=None, description="which report video to compose a description for"
    )


# ------------------------------------------------------------------------------------- helpers


def _meta_for(source_id: str) -> dict:
    """Read the corpus meta.json sitting beside a source file. Missing is not an error."""
    candidate = (REPO_ROOT / source_id).parent / "meta.json"
    if not candidate.is_file():
        return {}
    try:
        return json.loads(candidate.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def _load_report() -> dict:
    """Return `reports/latest.json`, enriched with the YouTube link each video needs.

    `report.VideoReport` carries no `video_id` — a link target is presentation, not part of a
    decision, so `report.py` is left alone and the join happens here.
    """
    if not REPORT_PATH.is_file():
        raise HTTPException(
            status_code=503,
            detail=(
                "reports/latest.json is missing. It is a build artifact and is gitignored; "
                "generate it with: python -m almanac scan --source corpus --out reports/"
            ),
        )
    try:
        report = json.loads(REPORT_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise HTTPException(status_code=500, detail=f"reports/latest.json is not valid JSON: {exc}")

    for video in report.get("videos", []):
        meta = _meta_for(video["source_id"])
        video_id = meta.get("video_id")
        video["video_id"] = video_id
        video["watch_url"] = f"https://www.youtube.com/watch?v={video_id}" if video_id else None
        video["description"] = meta.get("description")
        video["read_count"] = len(video.get("verdicts", []))
        video["flagged_count"] = sum(
            1 for row in video.get("verdicts", []) if row["status"] != "skip"
        )
        video["dominant_claim_type"] = _dominant_claim_type(video.get("verdicts", []))
    report["measured"] = MEASURED
    return report


def _dominant_claim_type(rows: list[dict]) -> str | None:
    """The claim_type most of a video's numbers carried.

    Used for the "N numbers read, 0 flagged (illustrative)" line. Computed from the rows rather
    than asserted, because the count varies run to run — see ADR-002 D-5, and the A-08 walkthrough
    finding. A page about honesty does not hardcode a number it did not measure.
    """
    if not rows:
        return None
    tally: dict[str, int] = {}
    for row in rows:
        tally[row["claim_type"]] = tally.get(row["claim_type"], 0) + 1
    return max(tally, key=lambda key: (tally[key], key))


def _rows_for_text(text: str) -> tuple[list[dict], str]:
    """extract -> judge -> notes on a pasted string. Returns (rows, source_id).

    Routed through `extract.read_source` rather than a local re-implementation: the locators the
    page shows are then the same ones `almanac lint` prints, by construction rather than by
    promise.
    """
    from almanac.cli import _judged
    from almanac.extract import read_source
    from almanac.report import to_row

    with tempfile.TemporaryDirectory() as tmp:
        scratch = Path(tmp) / "pasted.md"
        scratch.write_text(text, encoding="utf-8")
        source = read_source(scratch)

    source = dataclasses.replace(source, source_id="(pasted script)")
    judged, notes = _judged([source], draft_notes=True)
    rows = [to_row(verdict, notes) for verdict in judged[source.source_id]]
    return [json.loads(row.model_dump_json()) for row in rows], source.source_id


def compose_description(video: dict) -> dict:
    """The description a human would paste, and the diff against the one YouTube has now.

    Composed from notes `notes.py` already drafted for rows `judge.py` already ruled
    `stale_material`. Nothing here decides that a video needs a note.
    """
    current = video.get("description") or ""
    notes = [
        row["note"]
        for row in video.get("verdicts", [])
        if row["status"] == "stale_material" and row.get("note")
    ]

    if notes:
        block = "\n".join(notes)
        proposed = f"{current}\n\n{block}".strip("\n") if current else block
    else:
        proposed = current

    diff = "\n".join(
        difflib.unified_diff(
            current.splitlines(),
            proposed.splitlines(),
            fromfile=f"{video.get('video_id') or video['source_id']} (current)",
            tofile=f"{video.get('video_id') or video['source_id']} (proposed)",
            lineterm="",
        )
    )
    return {
        "source_id": video["source_id"],
        "video_id": video.get("video_id"),
        "title": video.get("title"),
        "current_description": current,
        "proposed_description": proposed,
        "diff": diff,
        "notes": notes,
        "note_count": len(notes),
        "changed": proposed != current,
    }


def _json(payload: dict, status_code: int = 200) -> JSONResponse:
    """Serialise dates the way the report already does, rather than letting them raise."""
    return JSONResponse(
        content=json.loads(json.dumps(payload, default=_default)), status_code=status_code
    )


def _default(value):
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    raise TypeError(f"not JSON serialisable: {type(value).__name__}")


# ----------------------------------------------------------------------------------- endpoints


@app.get("/")
def index() -> FileResponse:
    """The page itself. One file, inline CSS/JS, no build step."""
    if not INDEX_HTML.is_file():  # pragma: no cover - the file ships with the repo
        raise HTTPException(status_code=500, detail="web/static/index.html is missing")
    return FileResponse(INDEX_HTML, media_type="text/html")


@app.get("/api/report")
def api_report() -> JSONResponse:
    """The last scan, as written to disk. This endpoint never starts a scan."""
    return _json(_load_report())


@app.post("/api/lint")
def api_lint(request: LintRequest) -> JSONResponse:
    """Check one pasted script. The only endpoint that calls a model."""
    text = request.text or ""
    if not text.strip():
        raise HTTPException(status_code=422, detail="text is empty")
    if len(text) > MAX_LINT_CHARS:
        raise HTTPException(
            status_code=413,
            detail=f"text is {len(text):,} characters; the limit is {MAX_LINT_CHARS:,}",
        )

    started = time.monotonic()
    rows, source_id = _rows_for_text(text)
    elapsed_ms = int((time.monotonic() - started) * 1000)

    from almanac.report import counts_by_status

    class _Row:  # counts_by_status reads `.status`; the rows are dicts by this point
        __slots__ = ("status",)

        def __init__(self, status: str) -> None:
            self.status = status

    return _json({
        "source_id": source_id,
        "chars": len(text),
        "verdicts": rows,
        "counts": counts_by_status([_Row(row["status"]) for row in rows]),
        "elapsed_ms": elapsed_ms,
    })


@app.post("/api/apply")
def api_apply(request: ApplyRequest) -> JSONResponse:
    """The would-be description change. **Dry run, unconditionally.**

    This endpoint writes nothing and calls no YouTube API. It does not consult ALMANAC_WRITE:
    a web request cannot supply the `--apply` the Project Rules require, so there is no
    configuration under which it should write, and therefore no branch here that could.
    """
    report = _load_report()
    videos = report.get("videos", [])
    if request.source_id:
        videos = [v for v in videos if v["source_id"] == request.source_id]
        if not videos:
            raise HTTPException(status_code=404, detail=f"no video {request.source_id!r} in report")

    changes = [compose_description(video) for video in videos]
    return _json({
        "dry_run": True,
        "wrote": False,
        "write_attempted": False,
        "reason": (
            "A web request cannot supply the --apply the Project Rules require, so /api/apply "
            "is dry-run unconditionally: it does not read ALMANAC_WRITE and constructs no "
            "YouTube client. Paste the proposed description yourself, or use the CLI."
        ),
        "note_marker": NOTE_MARKER,
        "changes": changes,
        "changed_count": sum(1 for change in changes if change["changed"]),
    })


CORPUS_SCRIPTS = {"fresh_wrong": "fresh_wrong.md", "fresh_ok": "fresh_ok.md"}


@app.get("/api/scripts")
def api_scripts() -> JSONResponse:
    """The two demo scripts, read from `corpus/scripts/` at request time.

    A fifth endpoint the issue did not list, added for one reason: the page must preload
    `fresh_wrong.md` and swap in `fresh_ok.md`. Pasting copies of those files into index.html
    would fork protected `corpus/**` content into the web layer, where it would drift silently
    the first time either script changed. Read-only, no keys, no model call.
    """
    scripts = {}
    for name, filename in CORPUS_SCRIPTS.items():
        path = REPO_ROOT / "corpus" / "scripts" / filename
        scripts[name] = {
            "filename": f"corpus/scripts/{filename}",
            "text": path.read_text(encoding="utf-8") if path.is_file() else "",
        }
    return _json({"scripts": scripts})
