"""A-08: the two-pane web page. FastAPI serves a scan that already happened.

RULE, and it is the whole shape of this module: **the page reads, it does not decide.**
Nothing here judges anything. `GET /api/report` serves `reports/latest.json` verbatim;
`POST /api/lint` runs A-03's extractor and A-04's judge and hands back what they produced.
Every row that reaches the browser still carries the `rule_fired` that `judge.py` stamped on it.

Three things this module deliberately does NOT do:

1. **It does not scan on load.** `reports/latest.json` is a build artifact (gitignored,
   regenerated by `almanac scan`). A scan is ~30s of live model calls; a page that scanned on
   page-view would bill every visitor to Zaeem's API key. `/api/report` reads the file or says
   plainly that it is missing.
2. **It does not re-implement the pipeline.** `/api/lint` goes through `extract.read_source` and
   `cli._judged`, so a verdict on the page is the same object `almanac lint` prints. A second
   implementation here would be a second thing to keep true.
3. **It does not write to YouTube, under any configuration.** See the write guard below.

## The write guard

The Project Rules allow `videos.update` only when ALMANAC_WRITE=true AND the channel is
ALMANAC_TEST_CHANNEL_ID AND the CLI was given `--apply`. **A web request has no `--apply`, and
there is no way for a visitor to supply one.** So `/api/apply` is dry-run *unconditionally*: it
does not read ALMANAC_WRITE, does not import `almanac.youtube`, and constructs no API client.
It composes the description a human would paste and returns the diff.

That is stronger than "off by default" — a flag flipped in the environment cannot turn it on,
which `tests/test_web.py` proves by running the endpoint with ALMANAC_WRITE=true and counting
`videos.update` calls at the `googleapiclient.discovery.build` chokepoint.

## What the page may claim

Bounded by `docs/decisions/ADR-002-eval-loop.md` (A-05). The measured figures live in
`MEASURED` below rather than in the HTML, so the page cannot drift from the eval table without
this constant changing. Nothing on the page may claim more than A-05 measured.
"""

from __future__ import annotations

import dataclasses
import difflib
import json
import tempfile
import time
from datetime import date, datetime
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse, JSONResponse
from pydantic import BaseModel, Field

REPO_ROOT = Path(__file__).resolve().parents[1]
STATIC_DIR = Path(__file__).resolve().parent / "static"
INDEX_HTML = STATIC_DIR / "index.html"
REPORT_PATH = REPO_ROOT / "reports" / "latest.json"
CORPUS_CHANNEL = REPO_ROOT / "corpus" / "channel"

# The issue's cap. Enforced on the decoded string, not on the request body, because a multi-byte
# character is one character to the person who pasted it.
MAX_LINT_CHARS = 8_000

# The pin every drafted note opens with. `notes.py` ASKS the model for it in the prompt and its
# fallback template hard-codes it, but `check_note()` does not enforce it — so this is the label
# the page uses for the note block, not an invariant anything may assert on a model-written note.
NOTE_MARKER = "📌"

# Every figure the page is allowed to quote, with the run that produced it. A-05 / ADR-002.
# Kept here so a copy change cannot invent a number the eval table does not support.
MEASURED = {
    "source": "A-05 / ADR-002, live run 2026-09-07, 7 sources, 54 human-labelled rows",
    "extraction_recall": "89% (48/54)",
    "claim_type_accuracy": "98%",
    "stale_material_precision": "1.00",
    "stale_material_recall": "1.00",
    "hard_negative_false_positives": "0 of 22 matched illustrative/historical rows",
    "skip_recall": "0.81",
    "judge_status_disagreements": "0 across five live runs, all five statuses",
    "extraction_reproducible": False,
    "extraction_variance": "65-77 verdicts on identical input; the eval gate fails 2 runs in 5",
    # Corrected 2026-09-07 against ADR-000 §10. The earlier text here named `temperature` as the
    # cause and called the D-5 fix "not applied". BOTH halves were false: this model accepts no
    # sampling control at all (the SDK has no `temperature` parameter; `temperature`, `top_p` and
    # `top_k` return HTTP 400 "deprecated for this model", `seed` is rejected as an extra input),
    # and a fix HAS landed - the coverage sweep in `d314e9a`, which re-reads any number-bearing
    # sentence the first pass produced no claim for.
    "known_defect": (
        "This model exposes no sampling control - temperature, top_p, top_k and seed are all "
        "rejected by the API (ADR-000 §10) - so determinism cannot be requested and has to be "
        "enforced in code. A coverage sweep (d314e9a) now re-reads any number-bearing sentence "
        "the first pass produced no claim for."
    ),
    # The honesty rule turned on this page itself. Every figure above was measured by A-05 on the
    # extractor as it stood BEFORE the sweep landed, and this session could not re-measure: the
    # Anthropic credit balance is exhausted, so `almanac scan` returns HTTP 400. Whether the sweep
    # moves these numbers is UNMEASURED here, and the page says so rather than implying otherwise.
    "figures_predate_the_sweep": True,
    "sweep_measured_here": False,
    "unmeasured": (
        "The figures above were measured before the d314e9a coverage sweep landed, and the scan "
        "below is also a pre-sweep run. This page has not measured what the sweep changed."
    ),
}

app = FastAPI(title="Almanac", description="Checks the numbers in a back catalogue.")


# ------------------------------------------------------------------------------ request models


class LintRequest(BaseModel):
    text: str = Field(description="a script or caption block to check")


class ApplyRequest(BaseModel):
    source_id: str | None = Field(
        default=None, description="which report video to compose a description for"
    )


# ------------------------------------------------------------------------------------- helpers


def _meta_for(source_id: str) -> dict:
    """Read the corpus meta.json sitting beside a source file. Missing is not an error."""
    candidate = (REPO_ROOT / source_id).parent / "meta.json"
    if not candidate.is_file():
        return {}
    try:
        return json.loads(candidate.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def _load_report() -> dict:
    """Return `reports/latest.json`, enriched with the YouTube link each video needs.

    `report.VideoReport` carries no `video_id` — a link target is presentation, not part of a
    decision, so `report.py` is left alone and the join happens here.
    """
    if not REPORT_PATH.is_file():
        raise HTTPException(
            status_code=503,
            detail=(
                "reports/latest.json is missing. It is a build artifact and is gitignored; "
                "generate it with: python -m almanac scan --source corpus --out reports/"
            ),
        )
    try:
        report = json.loads(REPORT_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise HTTPException(status_code=500, detail=f"reports/latest.json is not valid JSON: {exc}")

    for video in report.get("videos", []):
        meta = _meta_for(video["source_id"])
        video_id = meta.get("video_id")
        video["video_id"] = video_id
        video["watch_url"] = f"https://www.youtube.com/watch?v={video_id}" if video_id else None
        video["description"] = meta.get("description")
        video["read_count"] = len(video.get("verdicts", []))
        video["flagged_count"] = sum(
            1 for row in video.get("verdicts", []) if row["status"] != "skip"
        )
        video["dominant_claim_type"] = _dominant_claim_type(video.get("verdicts", []))
    report["measured"] = MEASURED
    return report


def _dominant_claim_type(rows: list[dict]) -> str | None:
    """The claim_type most of a video's numbers carried.

    Used for the "N numbers read, 0 flagged (illustrative)" line. Computed from the rows rather
    than asserted, because the count varies run to run — see ADR-002 D-5, and the A-08 walkthrough
    finding. A page about honesty does not hardcode a number it did not measure.
    """
    if not rows:
        return None
    tally: dict[str, int] = {}
    for row in rows:
        tally[row["claim_type"]] = tally.get(row["claim_type"], 0) + 1
    return max(tally, key=lambda key: (tally[key], key))


def _rows_for_text(text: str) -> tuple[list[dict], str]:
    """extract -> judge -> notes on a pasted string. Returns (rows, source_id).

    Routed through `extract.read_source` rather than a local re-implementation: the locators the
    page shows are then the same ones `almanac lint` prints, by construction rather than by
    promise.
    """
    from almanac.cli import _judged
    from almanac.extract import read_source
    from almanac.report import to_row

    with tempfile.TemporaryDirectory() as tmp:
        scratch = Path(tmp) / "pasted.md"
        scratch.write_text(text, encoding="utf-8")
        source = read_source(scratch)

    source = dataclasses.replace(source, source_id="(pasted script)")
    judged, notes = _judged([source], draft_notes=True)
    rows = [to_row(verdict, notes) for verdict in judged[source.source_id]]
    return [json.loads(row.model_dump_json()) for row in rows], source.source_id


def compose_description(video: dict) -> dict:
    """The description a human would paste, and the diff against the one YouTube has now.

    Composed from notes `notes.py` already drafted for rows `judge.py` already ruled
    `stale_material`. Nothing here decides that a video needs a note.
    """
    current = video.get("description") or ""
    notes = [
        row["note"]
        for row in video.get("verdicts", [])
        if row["status"] == "stale_material" and row.get("note")
    ]

    if notes:
        block = "\n".join(notes)
        proposed = f"{current}\n\n{block}".strip("\n") if current else block
    else:
        proposed = current

    diff = "\n".join(
        difflib.unified_diff(
            current.splitlines(),
            proposed.splitlines(),
            fromfile=f"{video.get('video_id') or video['source_id']} (current)",
            tofile=f"{video.get('video_id') or video['source_id']} (proposed)",
            lineterm="",
        )
    )
    return {
        "source_id": video["source_id"],
        "video_id": video.get("video_id"),
        "title": video.get("title"),
        "current_description": current,
        "proposed_description": proposed,
        "diff": diff,
        "notes": notes,
        "note_count": len(notes),
        "changed": proposed != current,
    }


def _json(payload: dict, status_code: int = 200) -> JSONResponse:
    """Serialise dates the way the report already does, rather than letting them raise."""
    return JSONResponse(
        content=json.loads(json.dumps(payload, default=_default)), status_code=status_code
    )


def _default(value):
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    raise TypeError(f"not JSON serialisable: {type(value).__name__}")


# ----------------------------------------------------------------------------------- endpoints


@app.get("/")
def index() -> FileResponse:
    """The page itself. One file, inline CSS/JS, no build step."""
    if not INDEX_HTML.is_file():  # pragma: no cover - the file ships with the repo
        raise HTTPException(status_code=500, detail="web/static/index.html is missing")
    return FileResponse(INDEX_HTML, media_type="text/html")


@app.get("/api/report")
def api_report() -> JSONResponse:
    """The last scan, as written to disk. This endpoint never starts a scan."""
    return _json(_load_report())


@app.post("/api/lint")
def api_lint(request: LintRequest) -> JSONResponse:
    """Check one pasted script. The only endpoint that calls a model."""
    text = request.text or ""
    if not text.strip():
        raise HTTPException(status_code=422, detail="text is empty")
    if len(text) > MAX_LINT_CHARS:
        raise HTTPException(
            status_code=413,
            detail=f"text is {len(text):,} characters; the limit is {MAX_LINT_CHARS:,}",
        )

    started = time.monotonic()
    rows, source_id = _rows_for_text(text)
    elapsed_ms = int((time.monotonic() - started) * 1000)

    from almanac.report import counts_by_status

    class _Row:  # counts_by_status reads `.status`; the rows are dicts by this point
        __slots__ = ("status",)

        def __init__(self, status: str) -> None:
            self.status = status

    return _json({
        "source_id": source_id,
        "chars": len(text),
        "verdicts": rows,
        "counts": counts_by_status([_Row(row["status"]) for row in rows]),
        "elapsed_ms": elapsed_ms,
    })


@app.post("/api/apply")
def api_apply(request: ApplyRequest) -> JSONResponse:
    """The would-be description change. **Dry run, unconditionally.**

    This endpoint writes nothing and calls no YouTube API. It does not consult ALMANAC_WRITE:
    a web request cannot supply the `--apply` the Project Rules require, so there is no
    configuration under which it should write, and therefore no branch here that could.
    """
    report = _load_report()
    videos = report.get("videos", [])
    if request.source_id:
        videos = [v for v in videos if v["source_id"] == request.source_id]
        if not videos:
            raise HTTPException(status_code=404, detail=f"no video {request.source_id!r} in report")

    changes = [compose_description(video) for video in videos]
    return _json({
        "dry_run": True,
        "wrote": False,
        "write_attempted": False,
        "reason": (
            "A web request cannot supply the --apply the Project Rules require, so /api/apply "
            "is dry-run unconditionally: it does not read ALMANAC_WRITE and constructs no "
            "YouTube client. Paste the proposed description yourself, or use the CLI."
        ),
        "note_marker": NOTE_MARKER,
        "changes": changes,
        "changed_count": sum(1 for change in changes if change["changed"]),
    })


CORPUS_SCRIPTS = {"fresh_wrong": "fresh_wrong.md", "fresh_ok": "fresh_ok.md"}


@app.get("/api/scripts")
def api_scripts() -> JSONResponse:
    """The two demo scripts, read from `corpus/scripts/` at request time.

    A fifth endpoint the issue did not list, added for one reason: the page must preload
    `fresh_wrong.md` and swap in `fresh_ok.md`. Pasting copies of those files into index.html
    would fork protected `corpus/**` content into the web layer, where it would drift silently
    the first time either script changed. Read-only, no keys, no model call.
    """
    scripts = {}
    for name, filename in CORPUS_SCRIPTS.items():
        path = REPO_ROOT / "corpus" / "scripts" / filename
        scripts[name] = {
            "filename": f"corpus/scripts/{filename}",
            "text": path.read_text(encoding="utf-8") if path.is_file() else "",
        }
    return _json({"scripts": scripts})
